config/routes.rb
Rails.application.routes.draw do

   root 'static_pages#index'
   get '/about_us' => 'static_pages#about_us'
   get '/help' => 'static_pages#help'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
  def about_us
  end

  def help
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

	def get_title(title)
		 title.empty? ? "UCBtweet" : "#{title} | UCBtweet"
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= get_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">LuChEx</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">

          <li>
            <%= link_to 'Home',root_path%>
        </li>
        <li>
             <%= link_to 'About',about_us_path%>
       </li>
       <li>
             <%= link_to 'Help',help_path%>
       </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
           <li>
            <a href="#">Log In</a>
        </li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/static_pages/about_us.html.erb
<div class="jumbotron">
  <h1>Hola</h1>
  <p>Este grupo aprende Rails con pablo </p>
</div>

app/views/static_pages/help.html.erb
<div class="jumbotron">
  <h1>Ayuda ?</h1>
  <p>Pregunta a Ing Pablo</p>
  <%= image_tag  'banana.gif'%>
  <iframe width="854" height="480" src="https://www.youtube.com/embed/3TDaN6KOUf8" frameborder="0" allowfullscreen></iframe>
</div>

app/views/static_pages/index.html.erb
<div class="jumbotron">
  <h1 class="text-center">Hello</h1>
  <p>this is my first rails application</p>
</div>